[versions]
kotlin = "2.0.21"
fabric_loom = "1.8.9"

minecraft = "1.21.3"
yarnMapping = "1.21.3+build.2"
loader = "0.16.7"
kotlinLoader = "1.12.3+kotlin.2.0.21"
fabric = "0.106.1+1.21.3"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
fabricLoom = { id = "fabric-loom", version.ref = "fabric_loom" }

[libraries]
minecraft = { group = "com.mojang", name = "minecraft", version.ref = "minecraft" }
yarnMapping = { group = "net.fabricmc", name = "yarn", version.ref = "yarnMapping" }
loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "loader" }
kotlinLoader = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "kotlinLoader" }
fabric = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric" }

worldedit = { group = "com.sk89q.worldedit", name = "worldedit-fabric-mc1.21", version = "latest.release" }